// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE2vVdvoezTp5HGagF8NQn8lBmwKokd-c',
    appId: '1:811534522991:web:036ba04a73249f8fe68b9a',
    messagingSenderId: '811534522991',
    projectId: 'football-fantasy-app-498ac',
    authDomain: 'football-fantasy-app-498ac.firebaseapp.com',
    storageBucket: 'football-fantasy-app-498ac.firebasestorage.app',
    measurementId: 'G-MWM47G84JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxJan4eOFFWDsghUQY7g-Nf4vD2W3L6Rs',
    appId: '1:811534522991:android:c0cc3cf984a7587de68b9a',
    messagingSenderId: '811534522991',
    projectId: 'football-fantasy-app-498ac',
    storageBucket: 'football-fantasy-app-498ac.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN78_sUOLse9tUv_afd8KJ1mN7mMe96MY',
    appId: '1:811534522991:ios:738becb2db54d282e68b9a',
    messagingSenderId: '811534522991',
    projectId: 'football-fantasy-app-498ac',
    storageBucket: 'football-fantasy-app-498ac.firebasestorage.app',
    iosBundleId: 'com.example.footballManagerCompanionApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE2vVdvoezTp5HGagF8NQn8lBmwKokd-c',
    appId: '1:811534522991:web:89e06f442df4f144e68b9a',
    messagingSenderId: '811534522991',
    projectId: 'football-fantasy-app-498ac',
    authDomain: 'football-fantasy-app-498ac.firebaseapp.com',
    storageBucket: 'football-fantasy-app-498ac.firebasestorage.app',
    measurementId: 'G-SDDDZB3N6F',
  );
}
