import '../models/player.dart';

class MockData {
  static List<Player> getMockPlayers() {
    return [
      // Goalkeepers
      Player(
        id: '1',
        name: 'Manchester City GK',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.goalkeeper,
        price: 5.0,
        points: 450,
        gameweekPoints: 12,
        nationality: 'England',
      ),
      Player(
        id: '2',
        name: 'Liverpool GK',
        clubId: 'liv',
        clubName: 'Liverpool',
        position: PlayerPosition.goalkeeper,
        price: 5.5,
        points: 480,
        gameweekPoints: 14,
        nationality: 'Brazil',
      ),

      // Defenders
      Player(
        id: '3',
        name: 'Van Dijk',
        clubId: 'liv',
        clubName: 'Liverpool',
        position: PlayerPosition.defender,
        price: 6.5,
        points: 520,
        gameweekPoints: 15,
        nationality: 'Netherlands',
        cleanSheets: 8,
      ),
      Player(
        id: '4',
        name: 'Stones',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.defender,
        price: 6.0,
        points: 500,
        gameweekPoints: 13,
        nationality: 'England',
        cleanSheets: 7,
      ),
      Player(
        id: '5',
        name: 'Salah',
        clubId: 'liv',
        clubName: 'Liverpool',
        position: PlayerPosition.defender,
        price: 6.8,
        points: 540,
        gameweekPoints: 16,
        nationality: 'Egypt',
        goalsScored: 5,
        assists: 3,
      ),
      Player(
        id: '6',
        name: 'Arnold',
        clubId: 'liv',
        clubName: 'Liverpool',
        position: PlayerPosition.defender,
        price: 6.2,
        points: 510,
        gameweekPoints: 14,
        nationality: 'England',
        cleanSheets: 6,
      ),
      Player(
        id: '7',
        name: 'Cancelo',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.defender,
        price: 6.7,
        points: 530,
        gameweekPoints: 15,
        nationality: 'Portugal',
        assists: 4,
      ),

      // Midfielders
      Player(
        id: '8',
        name: 'De Bruyne',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.midfielder,
        price: 8.5,
        points: 680,
        gameweekPoints: 20,
        nationality: 'Belgium',
        goalsScored: 6,
        assists: 5,
      ),
      Player(
        id: '9',
        name: 'Maddison',
        clubId: 'tot',
        clubName: 'Tottenham',
        position: PlayerPosition.midfielder,
        price: 7.5,
        points: 620,
        gameweekPoints: 18,
        nationality: 'England',
        goalsScored: 4,
        assists: 3,
      ),
      Player(
        id: '10',
        name: 'Rodri',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.midfielder,
        price: 8.0,
        points: 650,
        gameweekPoints: 19,
        nationality: 'Spain',
        goalsScored: 2,
        assists: 2,
      ),
      Player(
        id: '11',
        name: 'Foden',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.midfielder,
        price: 8.3,
        points: 670,
        gameweekPoints: 19,
        nationality: 'England',
        goalsScored: 5,
        assists: 4,
      ),
      Player(
        id: '12',
        name: 'Son',
        clubId: 'tot',
        clubName: 'Tottenham',
        position: PlayerPosition.midfielder,
        price: 7.8,
        points: 640,
        gameweekPoints: 18,
        nationality: 'South Korea',
        goalsScored: 7,
        assists: 2,
      ),

      // Forwards
      Player(
        id: '13',
        name: 'Haaland',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.forward,
        price: 12.0,
        points: 890,
        gameweekPoints: 25,
        nationality: 'Norway',
        goalsScored: 18,
        assists: 3,
      ),
      Player(
        id: '14',
        name: 'Nunez',
        clubId: 'liv',
        clubName: 'Liverpool',
        position: PlayerPosition.forward,
        price: 9.0,
        points: 720,
        gameweekPoints: 21,
        nationality: 'Uruguay',
        goalsScored: 12,
        assists: 2,
      ),
      Player(
        id: '15',
        name: 'Richarlison',
        clubId: 'tot',
        clubName: 'Tottenham',
        position: PlayerPosition.forward,
        price: 8.2,
        points: 660,
        gameweekPoints: 19,
        nationality: 'Brazil',
        goalsScored: 10,
        assists: 3,
      ),
      
      // Additional players to have more options
      Player(
        id: '16',
        name: 'Arsenal GK',
        clubId: 'ars',
        clubName: 'Arsenal',
        position: PlayerPosition.goalkeeper,
        price: 5.2,
        points: 460,
        gameweekPoints: 13,
        nationality: 'England',
      ),
      Player(
        id: '17',
        name: 'Saka',
        clubId: 'ars',
        clubName: 'Arsenal',
        position: PlayerPosition.defender,
        price: 6.3,
        points: 515,
        gameweekPoints: 14,
        nationality: 'England',
        goalsScored: 1,
        assists: 2,
      ),
      Player(
        id: '18',
        name: 'Martinelli',
        clubId: 'ars',
        clubName: 'Arsenal',
        position: PlayerPosition.midfielder,
        price: 7.2,
        points: 600,
        gameweekPoints: 17,
        nationality: 'Brazil',
        goalsScored: 4,
        assists: 2,
      ),
      Player(
        id: '19',
        name: 'Jesus',
        clubId: 'ars',
        clubName: 'Arsenal',
        position: PlayerPosition.forward,
        price: 8.5,
        points: 700,
        gameweekPoints: 20,
        nationality: 'Brazil',
        goalsScored: 9,
        assists: 2,
      ),
      Player(
        id: '20',
        name: 'Ruiz',
        clubId: 'ful',
        clubName: 'Fulham',
        position: PlayerPosition.midfielder,
        price: 7.0,
        points: 580,
        gameweekPoints: 16,
        nationality: 'Portugal',
        goalsScored: 2,
        assists: 1,
      ),
    ];
  }
}
