import '../models/player.dart';

class MockData {
  static List<Player> getMockPlayers() {
    return const [
      // Goalkeepers
      Player(
        id: 'p1',
        name: 'Ederson',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.goalkeeper,
        price: 5.5,
        points: 120,
        gameweekPoints: 6,
        nationality: 'Brazil',
      ),
      Player(
        id: 'p2',
        name: 'Alisson',
        clubId: 'liv',
        clubName: 'Liverpool',
        position: PlayerPosition.goalkeeper,
        price: 5.5,
        points: 115,
        gameweekPoints: 4,
        nationality: 'Brazil',
      ),

      // Defenders
      Player(
        id: 'p3',
        name: 'Van Dijk',
        clubId: 'liv',
        clubName: 'Liverpool',
        position: PlayerPosition.defender,
        price: 6.5,
        points: 140,
        gameweekPoints: 8,
        nationality: 'Netherlands',
      ),
      Player(
        id: 'p4',
        name: 'Saliba',
        clubId: 'ars',
        clubName: 'Arsenal',
        position: PlayerPosition.defender,
        price: 6.0,
        points: 132,
        gameweekPoints: 7,
        nationality: 'France',
      ),
      Player(
        id: 'p5',
        name: 'Gabriel',
        clubId: 'ars',
        clubName: 'Arsenal',
        position: PlayerPosition.defender,
        price: 6.0,
        points: 129,
        gameweekPoints: 6,
        nationality: 'Brazil',
      ),
      Player(
        id: 'p6',
        name: 'Walker',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.defender,
        price: 5.5,
        points: 110,
        gameweekPoints: 2,
        nationality: 'England',
      ),
      Player(
        id: 'p7',
        name: 'Udogie',
        clubId: 'tot',
        clubName: 'Tottenham',
        position: PlayerPosition.defender,
        price: 5.0,
        points: 104,
        gameweekPoints: 5,
        nationality: 'Italy',
      ),

      // Midfielders
      Player(
        id: 'p8',
        name: 'Salah',
        clubId: 'liv',
        clubName: 'Liverpool',
        position: PlayerPosition.midfielder,
        price: 12.5,
        points: 180,
        gameweekPoints: 12,
        nationality: 'Egypt',
      ),
      Player(
        id: 'p9',
        name: 'De Bruyne',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.midfielder,
        price: 10.5,
        points: 150,
        gameweekPoints: 10,
        nationality: 'Belgium',
      ),
      Player(
        id: 'p10',
        name: 'Saka',
        clubId: 'ars',
        clubName: 'Arsenal',
        position: PlayerPosition.midfielder,
        price: 9.0,
        points: 154,
        gameweekPoints: 9,
        nationality: 'England',
      ),
      Player(
        id: 'p11',
        name: 'Son',
        clubId: 'tot',
        clubName: 'Tottenham',
        position: PlayerPosition.midfielder,
        price: 9.5,
        points: 148,
        gameweekPoints: 11,
        nationality: 'South Korea',
      ),
      Player(
        id: 'p12',
        name: 'Foden',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.midfielder,
        price: 8.0,
        points: 142,
        gameweekPoints: 6,
        nationality: 'England',
      ),

      // Forwards
      Player(
        id: 'p13',
        name: 'Haaland',
        clubId: 'mci',
        clubName: 'Manchester City',
        position: PlayerPosition.forward,
        price: 14.0,
        points: 200,
        gameweekPoints: 13,
        nationality: 'Norway',
      ),
      Player(
        id: 'p14',
        name: 'Watkins',
        clubId: 'avl',
        clubName: 'Aston Villa',
        position: PlayerPosition.forward,
        price: 8.5,
        points: 138,
        gameweekPoints: 7,
        nationality: 'England',
      ),
      Player(
        id: 'p15',
        name: 'Isak',
        clubId: 'new',
        clubName: 'Newcastle',
        position: PlayerPosition.forward,
        price: 8.0,
        points: 130,
        gameweekPoints: 8,
        nationality: 'Sweden',
      ),
    ];
  }
}
